before_script:
  - "mysql -e 'create database by_star_test;'"
  - "psql -c 'create database by_star_test;' -U postgres"

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
  - ACTIVE_RECORD_VERSION=4.0.0 MONGOID_VERSION=master DB=sqlite
  - ACTIVE_RECORD_VERSION=4.0.0 MONGOID_VERSION=master DB=mysql
  - ACTIVE_RECORD_VERSION=4.0.0 MONGOID_VERSION=master DB=postgres

notifications:
  email:
    - radarlistener@gmail.com

branches:
  only:
    - master

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx
  - jruby

matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby

services: mongodb
