before_script:
  - "mysql -e 'create database by_star_test;'"
  - "psql -c 'create database by_star_test;' -U postgres"

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
  - DB=mongodb

gemfile:
  - spec/gemfiles/Gemfile.rails32
  - spec/gemfiles/Gemfile.rails40
  - spec/gemfiles/Gemfile.rails41
  - spec/gemfiles/Gemfile.rails42
  - spec/gemfiles/Gemfile.master

notifications:
  email:
    - radarlistener@gmail.com

branches:
  only:
    - master

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - rbx
  - jruby

matrix:
  exclude:
    - rvm: 2.2.0
      gemfile: spec/gemfiles/Gemfile.rails32
  allow_failures:
    - rvm: rbx
    - rvm: jruby
    - gemfile: spec/gemfiles/Gemfile.master

services: mongodb
